// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using upmData.Context;

#nullable disable

namespace upmData.Migrations
{
    [DbContext(typeof(UpmwebContext))]
    [Migration("20250819171944_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Modern_Spanish_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("upmData.Models.Downtime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InforCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDirectDowntime")
                        .HasColumnType("bit");

                    b.Property<string>("Plccode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PLCCode");

                    b.Property<bool>("Programable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Downtime", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.DowntimeRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DowntimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartNumberConfigurationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DowntimeId" }, "IX_DowntimeRegister_DowntimeId");

                    b.HasIndex(new[] { "PartNumberConfigurationId" }, "IX_DowntimeRegister_PartNumberConfigurationId");

                    b.ToTable("DowntimeRegister", "upmap");
                });

            modelBuilder.Entity("upmData.Models.DowntimeRegisterResponsable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CodeUser")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DowntimeRegisterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DowntimeRegisterId" }, "IX_DowntimeRegister_Responsables_DowntimeRegisterId");

                    b.ToTable("DowntimeRegister_Responsables", "upmap");
                });

            modelBuilder.Entity("upmData.Models.EmployeeReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CodeUser")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LineId" }, "IX_EmployeeReport_LineId");

                    b.HasIndex(new[] { "WorkShiftId" }, "IX_EmployeeReport_WorkShiftId");

                    b.ToTable("EmployeeReport", "upmap");
                });

            modelBuilder.Entity("upmData.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLog", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.LiderConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartNumberConfigurationId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PartNumberConfigurationId" }, "IX_LiderConfiguration_PartNumberConfigurationId");

                    b.HasIndex(new[] { "UserId" }, "IX_LiderConfiguration_UserId");

                    b.ToTable("LiderConfiguration", "upmconf");
                });

            modelBuilder.Entity("upmData.Models.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CodeLine")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlcIp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PLC_IP");

                    b.Property<string>("WorkCenter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Line", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.MaterialAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NotifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartNumberConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PartNumberConfigurationId" }, "IX_MaterialAlerts_PartNumberConfigurationId");

                    b.ToTable("MaterialAlerts", "upmsh");
                });

            modelBuilder.Entity("upmData.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Model", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.PartNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("NetoTime")
                        .HasColumnType("real");

                    b.Property<float>("ObjectiveTime")
                        .HasColumnType("real");

                    b.Property<string>("PartNumberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PartNumber", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.PartNumberConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LiderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("PartNumberCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PartNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupplyAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("01d1daf8-ab61-42f6-8520-cb1afe9807cd"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "LineId" }, "IX_PartNumberConfiguration_LineId");

                    b.HasIndex(new[] { "ModelId" }, "IX_PartNumberConfiguration_ModelId");

                    b.HasIndex(new[] { "PartNumberId" }, "IX_PartNumberConfiguration_PartNumberId")
                        .IsUnique();

                    b.HasIndex(new[] { "SupplyAreaId" }, "IX_PartNumberConfiguration_SupplyAreaId");

                    b.ToTable("PartNumberConfiguration", "upmconf");
                });

            modelBuilder.Entity("upmData.Models.ProductionRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PartNumberConfigurationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PartNumberConfigurationId" }, "IX_ProductionRegister_PartNumberConfigurationId");

                    b.ToTable("ProductionRegister", "upmap");
                });

            modelBuilder.Entity("upmData.Models.RackRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoRack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoRACK");

                    b.Property<int>("PartNumberConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PartNumberConfigurationId" }, "IX_RackRegister_PartNumberConfigurationId");

                    b.ToTable("RackRegister", "upmap");
                });

            modelBuilder.Entity("upmData.Models.RequerimentsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartNumberConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Plant01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plant02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Production")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("RanQuantity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PartNumberConfigurationId" }, "IX_RequerimentsHistory_PartNumberConfigurationId");

                    b.ToTable("RequerimentsHistory", "upmpc");
                });

            modelBuilder.Entity("upmData.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Description" }, "IX_Role_Description")
                        .IsUnique();

                    b.ToTable("Role", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.SupplyArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Description" }, "IX_SupplyArea_Description")
                        .IsUnique();

                    b.ToTable("SupplyArea", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CodeUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CodeUser" }, "IX_User_CodeUser")
                        .IsUnique();

                    b.ToTable("User", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.UserConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleID");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_UserConfiguration_RoleID");

                    b.HasIndex(new[] { "UserId" }, "IX_UserConfiguration_UserID");

                    b.ToTable("UserConfiguration", "upmconf");
                });

            modelBuilder.Entity("upmData.Models.ViewActiveColaboradore", b =>
                {
                    b.Property<string>("CbApeMat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CB_APE_MAT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CbApePat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CB_APE_PAT")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CbCodigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CB_CODIGO")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CbNombres")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CB_NOMBRES")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Prettyname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PRETTYNAME")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.ToTable((string)null);

                    b.ToView("View_ActiveColaboradores", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.ViewComponentsTree", b =>
                {
                    b.Property<string>("Descripcion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Estructura")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Familia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nivel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Producto")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Sitio")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Unidad")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal?>("Usage")
                        .HasColumnType("decimal(18, 4)");

                    b.ToTable((string)null);

                    b.ToView("View_ComponentsTree", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.WorkShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("SecondsQuantity")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WorkShift", "upmdat");
                });

            modelBuilder.Entity("upmData.Models.DowntimeRegister", b =>
                {
                    b.HasOne("upmData.Models.Downtime", "Downtime")
                        .WithMany("DowntimeRegisters")
                        .HasForeignKey("DowntimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("upmData.Models.PartNumberConfiguration", "PartNumberConfiguration")
                        .WithMany("DowntimeRegisters")
                        .HasForeignKey("PartNumberConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Downtime");

                    b.Navigation("PartNumberConfiguration");
                });

            modelBuilder.Entity("upmData.Models.DowntimeRegisterResponsable", b =>
                {
                    b.HasOne("upmData.Models.DowntimeRegister", "DowntimeRegister")
                        .WithMany("DowntimeRegisterResponsables")
                        .HasForeignKey("DowntimeRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DowntimeRegister");
                });

            modelBuilder.Entity("upmData.Models.EmployeeReport", b =>
                {
                    b.HasOne("upmData.Models.Line", "Line")
                        .WithMany("EmployeeReports")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("upmData.Models.WorkShift", "WorkShift")
                        .WithMany("EmployeeReports")
                        .HasForeignKey("WorkShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("upmData.Models.LiderConfiguration", b =>
                {
                    b.HasOne("upmData.Models.PartNumberConfiguration", "PartNumberConfiguration")
                        .WithMany("LiderConfigurations")
                        .HasForeignKey("PartNumberConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("upmData.Models.User", "User")
                        .WithMany("LiderConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartNumberConfiguration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("upmData.Models.MaterialAlert", b =>
                {
                    b.HasOne("upmData.Models.PartNumberConfiguration", "PartNumberConfiguration")
                        .WithMany("MaterialAlerts")
                        .HasForeignKey("PartNumberConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartNumberConfiguration");
                });

            modelBuilder.Entity("upmData.Models.PartNumberConfiguration", b =>
                {
                    b.HasOne("upmData.Models.Line", "Line")
                        .WithMany("PartNumberConfigurations")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("upmData.Models.Model", "Model")
                        .WithMany("PartNumberConfigurations")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("upmData.Models.PartNumber", "PartNumber")
                        .WithOne("PartNumberConfiguration")
                        .HasForeignKey("upmData.Models.PartNumberConfiguration", "PartNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("upmData.Models.SupplyArea", "SupplyArea")
                        .WithMany("PartNumberConfigurations")
                        .HasForeignKey("SupplyAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("upmData.Models.User", "User")
                        .WithMany("PartNumberConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("Model");

                    b.Navigation("PartNumber");

                    b.Navigation("SupplyArea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("upmData.Models.ProductionRegister", b =>
                {
                    b.HasOne("upmData.Models.PartNumberConfiguration", "PartNumberConfiguration")
                        .WithMany("ProductionRegisters")
                        .HasForeignKey("PartNumberConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartNumberConfiguration");
                });

            modelBuilder.Entity("upmData.Models.RackRegister", b =>
                {
                    b.HasOne("upmData.Models.PartNumberConfiguration", "PartNumberConfiguration")
                        .WithMany("RackRegisters")
                        .HasForeignKey("PartNumberConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartNumberConfiguration");
                });

            modelBuilder.Entity("upmData.Models.RequerimentsHistory", b =>
                {
                    b.HasOne("upmData.Models.PartNumberConfiguration", "PartNumberConfiguration")
                        .WithMany("RequerimentsHistories")
                        .HasForeignKey("PartNumberConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartNumberConfiguration");
                });

            modelBuilder.Entity("upmData.Models.UserConfiguration", b =>
                {
                    b.HasOne("upmData.Models.Role", "Role")
                        .WithMany("UserConfigurations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("upmData.Models.User", "User")
                        .WithMany("UserConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("upmData.Models.Downtime", b =>
                {
                    b.Navigation("DowntimeRegisters");
                });

            modelBuilder.Entity("upmData.Models.DowntimeRegister", b =>
                {
                    b.Navigation("DowntimeRegisterResponsables");
                });

            modelBuilder.Entity("upmData.Models.Line", b =>
                {
                    b.Navigation("EmployeeReports");

                    b.Navigation("PartNumberConfigurations");
                });

            modelBuilder.Entity("upmData.Models.Model", b =>
                {
                    b.Navigation("PartNumberConfigurations");
                });

            modelBuilder.Entity("upmData.Models.PartNumber", b =>
                {
                    b.Navigation("PartNumberConfiguration");
                });

            modelBuilder.Entity("upmData.Models.PartNumberConfiguration", b =>
                {
                    b.Navigation("DowntimeRegisters");

                    b.Navigation("LiderConfigurations");

                    b.Navigation("MaterialAlerts");

                    b.Navigation("ProductionRegisters");

                    b.Navigation("RackRegisters");

                    b.Navigation("RequerimentsHistories");
                });

            modelBuilder.Entity("upmData.Models.Role", b =>
                {
                    b.Navigation("UserConfigurations");
                });

            modelBuilder.Entity("upmData.Models.SupplyArea", b =>
                {
                    b.Navigation("PartNumberConfigurations");
                });

            modelBuilder.Entity("upmData.Models.User", b =>
                {
                    b.Navigation("LiderConfigurations");

                    b.Navigation("PartNumberConfigurations");

                    b.Navigation("UserConfigurations");
                });

            modelBuilder.Entity("upmData.Models.WorkShift", b =>
                {
                    b.Navigation("EmployeeReports");
                });
#pragma warning restore 612, 618
        }
    }
}
