// <auto-generated />
using System;
using LogicData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicData.Migrations.Temporal
{
    [DbContext(typeof(TemporalContext))]
    [Migration("20251221193645_createTable_OperationalEfficiency")]
    partial class createTable_OperationalEfficiency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("upm_temporal")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.Models._05_Temporal.OperationalEfficiency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("DowntimePercent")
                        .HasColumnType("real");

                    b.Property<float>("HP")
                        .HasColumnType("real");

                    b.Property<string>("Leader")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Neck")
                        .HasColumnType("real");

                    b.Property<float>("NetoProduictiveTime")
                        .HasColumnType("real");

                    b.Property<float>("NetoWorkingTime")
                        .HasColumnType("real");

                    b.Property<float>("NoProgramabeDowntimeTime")
                        .HasColumnType("real");

                    b.Property<float>("NoProgramableDowntimePercent")
                        .HasColumnType("real");

                    b.Property<float>("NoReportedTime")
                        .HasColumnType("real");

                    b.Property<float>("OperativityPercent")
                        .HasColumnType("real");

                    b.Property<Guid?>("PartNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartNumberName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<float>("PriductionReal")
                        .HasColumnType("real");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("ProgramabeDowntimeTime")
                        .HasColumnType("real");

                    b.Property<float>("ProgramableDowntimePercent")
                        .HasColumnType("real");

                    b.Property<float>("RealTime")
                        .HasColumnType("real");

                    b.Property<float>("RealWorkingTime")
                        .HasColumnType("real");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("TotalDowntime")
                        .HasColumnType("real");

                    b.Property<float>("TotalTime")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("OperationalEfficiency", "upm_temporal");
                });

            modelBuilder.Entity("Entity.Models._05_Temporal.ProductionAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Leader")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("PartNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartNumberName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("ProductionObjetive")
                        .HasColumnType("real");

                    b.Property<float>("ProductionReal")
                        .HasColumnType("real");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("WorkingTime")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ProductionAchievement", "upm_temporal");
                });
#pragma warning restore 612, 618
        }
    }
}
