// <auto-generated />
using System;
using LogicData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicData.Migrations.ProductionControl
{
    [DbContext(typeof(ProductionControlContext))]
    [Migration("20260217163614_createTable_PartNumberStructure")]
    partial class createTable_PartNumberStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("upm_productionControl")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.Models.ProductionControl.ComponentAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CancelBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompleteBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriticalBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CriticalDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PartNumberLogisticsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartNumberLogisticsId");

                    b.HasIndex("StatusId");

                    b.ToTable("ComponentAlert", "upm_productionControl");
                });

            modelBuilder.Entity("Entity.Models.ProductionControl.MaterialSupplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaterialSupplierDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MaterialSuplier", "upm_productionControl");
                });

            modelBuilder.Entity("Entity.Models.ProductionControl.PartNumberLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PartNumberId");

                    b.ToTable("PartNumberLocation", "upm_productionControl");
                });

            modelBuilder.Entity("Entity.Models.ProductionControl.PartNumberLogistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("SNP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PartNumberId");

                    b.ToTable("PartNumberLogistics", "upm_productionControl");
                });

            modelBuilder.Entity("Entity.Models.ProductionControl.PartNumberStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaterialSuplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartNumberDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PartNumberLogisticsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartNumberName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("ProductionStationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaterialSuplierId");

                    b.HasIndex("PartNumberLogisticsId");

                    b.HasIndex("ProductionStationId");

                    b.ToTable("PartNumberStructure", "upm_productionControl");
                });

            modelBuilder.Entity("Entity.Models.ProductionControl.ComponentAlert", b =>
                {
                    b.HasOne("Entity.Models.ProductionControl.PartNumberLogistics", "PartNumberLogistics")
                        .WithMany("ComponentAlerts")
                        .HasForeignKey("PartNumberLogisticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartNumberLogistics");
                });

            modelBuilder.Entity("Entity.Models.ProductionControl.PartNumberStructure", b =>
                {
                    b.HasOne("Entity.Models.ProductionControl.MaterialSupplier", "MaterialSupplier")
                        .WithMany("PartNumberStructures")
                        .HasForeignKey("MaterialSuplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Models.ProductionControl.PartNumberLogistics", "PartNumberLogistics")
                        .WithMany("PartNumberStructures")
                        .HasForeignKey("PartNumberLogisticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialSupplier");

                    b.Navigation("PartNumberLogistics");
                });

            modelBuilder.Entity("Entity.Models.ProductionControl.MaterialSupplier", b =>
                {
                    b.Navigation("PartNumberStructures");
                });

            modelBuilder.Entity("Entity.Models.ProductionControl.PartNumberLogistics", b =>
                {
                    b.Navigation("ComponentAlerts");

                    b.Navigation("PartNumberStructures");
                });
#pragma warning restore 612, 618
        }
    }
}
